version: '3'
name: ecommerce-monolith
services:
  em-app:
    image: viniciussantos/ecommerce-monolith:1.0.0-SNAPSHOT
    ports:
      - 8080:8080
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
      DATABASE_HOST: em-postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: postgres
      DATABASE_URL: postgresql://em-postgres:5432/postgres
      REDIS_HOST: em-redis
      REDIS_PORT: 6379
    depends_on:
      - em-postgres
      - em-redis

  em-postgres:
    container_name: em-postgres
    image: postgres:13.2
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    ports:
      - 5499:5432

  em-redis:
    image: redis:6.2.1
    ports:
      - 6399:6379
