version: '3'
name: ecommerce-monolith
services:
  em-app:
    image: viniciussantos/ecommerce-monolith:1.0.0-SNAPSHOT
    ports:
      - 8080:8080
    environment:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
      DATABASE_HOST: em-postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: postgres
      DATABASE_VERSION: 13.2
      REDIS_HOST: em-redis
      REDIS_PORT: 6379
    depends_on:
      - em-postgres
      - em-redis
    networks:
      - ecommerce-network