apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: quarkus-ecommerce-k8s-cluster

nodes:
# the control plane node config
- role: control-plane
  kubeadmConfigPatches:
  # node-labels only allow the ingress controller to run on a specific node(s) matching the label selector
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  # allow the local host to make requests to the Ingress controller over ports 80/443
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
# the three workers
- role: worker
- role: worker
- role: worker