apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-monolith
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-monolith
  template:
    metadata:
      labels:
        app: postgres-monolith
    spec:
      containers:
      - image: postgres:14-alpine
        name: postgres-monolith
        ports:
        - name: postgres
          containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: monolith-secrets
              key: database_username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: monolith-secrets
              key: database_password
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: monolith-config
              key: database_name
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata