apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-monolith-pv
spec:
  storageClassName: 'standard'
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-monolith-pvc
spec:
  storageClassName: 'standard'
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-monolith
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-monolith
  template:
    metadata:
      labels:
        app: postgres-monolith
    spec:
      containers:
      - image: postgres:14-alpine
        name: postgres-monolith
        ports:
        - name: postgres
          containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: monolith-secrets
              key: database_username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: monolith-secrets
              key: database_password
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: monolith-config
              key: database_name
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
          - name: postgres-monolith-storage
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-monolith-storage
          persistentVolumeClaim:
            claimName: postgres-monolith-pvc