name: Ecommerce Monolith Quarkus CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test pipeline
        run: ls -la

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # - name: Build the Docker image
      #   run: docker build -t viniciussantos/ecommerce-monolith:1.0.0-SNAPSHOT .

      # - name: Push the Docker image
      #   run: docker push viniciussantos/ecommerce-monolith:1.0.0-SNAPSHOT

      # - name: Deploy to Docker Compose
      #   run: docker-compose -f infra/compose.dev.yaml up -d

      # - name: Run tests
      #   run: mvn test

      # - name: Stop Docker Compose
      #   run: docker-compose -f infra/compose.dev.yaml down

      # - name: Deploy to Kubernetes
      #   run: kubectl apply -f infra/k8s.yaml

      # - name: Run tests
      #   run: mvn test

      # - name: Stop Kubernetes
      #   run: kubectl delete -f infra/k8s.yaml

      # - name: Deploy to Heroku
      #   run: heroku container:push web -a ecommerce-monolith
      #   env:
      #     HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      # - name: Release to Heroku
      #   run: heroku container:release web -a ecommerce-monolith
      #   env:
      #     HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}